### ISSUE TITLE
Making this extension compatible with modeline from vim

### ISSUE THREAD

**Issue by msgongora** [deitry/vscode-properties-language-alternative#2]
Hi @deitry, 
Would you be willing to rename the language id to make this extension compatible with modeline from vim supported by [this other extension](https://marketplace.visualstudio.com/items?itemName=chrislajoie.vscode-modelines)

Vim currently recognize this type of files as `dosini`, so by renaming the language id `properties-alternative` with `dosini` and having a modeline in your properties file as follow, vscode should be able to associate automatically the file type.

```
# ex: ft=dosini:
```

**Comment by deitry** [comment]
I just pushed updated version with language id alias.
https://code.visualstudio.com/docs/languages/identifiers

Could you please check if this helps?

**Comment by deitry** [comment]
Apparently this was not enough. I'll switch language id, that's not a problem

**Comment by deitry** [comment]
Should be fine since 0.0.3
